### ISSUE TITLE
FD-007.3 Customize styling member app google form

### ISSUE THREAD

**Issue by Sydnee510** [Young-N-Ambitious/yna_frontend#117]
**We will be keeping our current google form instead of building a new form to store our user data. The current google member form will be used for our users to sign up to be on our app. Now we want to customize the styling to match our theme**

Since we have embedded the Google Form in our website and want to customize the CSS to match the theme of our website, we can achieve this by applying custom CSS styles to the elements of the embedded form. Here's how we can do it:

Step 1: Identify the Google Form Elements

Inspect the elements of the embedded Google Form using your browser's developer tools. This will help you identify the HTML structure and classes used by the form elements. You can right-click on the form fields and choose "Inspect" or "Inspect Element" to open the developer tools.

Step 2: Create Custom CSS

In your website's CSS file, you can create custom CSS rules to target and style the specific form elements you identified in Step 1. You can override the default styles provided by Google Forms with your own styles to match your website's theme.

For example, let's say your embedded Google Form has a text input field with the class "entry-field". You can style it with the following custom CSS:

```css
/* Example custom CSS to style the text input field */
.entry-field {
  background-color: #f5f5f5; /* Change the background color */
  border: 1px solid #ccc; /* Change the border */
  padding: 10px; /* Add padding */
  color: #333; /* Change the text color */
  font-size: 14px; /* Change the font size */
  /* Add any other styles you want to customize */
}
```

You can apply similar custom CSS rules to other form elements like checkboxes, radio buttons, select dropdowns, etc., to style them according to your website's theme.

Step 3: Include Custom CSS in Your Website

Make sure to include your custom CSS file in your website's HTML. You can link the CSS file in the `<head>` section of your website's HTML code:

```html
<head>
  <!-- Other meta tags and links -->
  <link rel="stylesheet" href="path/to/your/custom.css">
</head>
```

Step 4: Test and Refine

After applying your custom CSS, test your embedded Google Form to ensure that the styles are as you intended. You may need to make adjustments to the CSS as necessary to fine-tune the appearance and ensure it matches your website's theme.

Remember that the ability to customize the form's appearance through CSS is limited to the elements exposed by Google Forms. More advanced customizations might not be possible through CSS alone.

As a best practice, always test the form on various devices and browsers to ensure it looks good and functions well across different platforms.

Use this figma as a reference:

![Screen Shot 2023-07-28 at 11 18 40 PM](https://github.com/Young-N-Ambitious/yna_frontend/assets/30539832/0bea72dc-ccd6-4eda-9522-985071f7954e)
